[project]
name = "ieta-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.1",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "uvicorn>=0.40.0",
]
